# fly.toml app configuration file generated for muddy-grass-5279 on 2023-11-05T23:50:55+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "muddy-grass-5279"
primary_region = "waw"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  DB_CONNECTION = "mysql"
  DB_HOST = "late-pine-2833.internal"
  DB_DATABASE= "some_db"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
